window.PORTFOLIO_PROJECTS = [
  {
    "id": "micro-shelter",
    "title": "Micro Shelter",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/micro-shelter/micro-shelter-001.jpg",
    "images": [
      "public/portfolio/full/micro-shelter/micro-shelter-001.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-002.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-003.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-004.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-005.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-006.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-007.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-008.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-009.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-010.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-011.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-012.png",
      "public/portfolio/full/micro-shelter/micro-shelter-013.png",
      "public/portfolio/full/micro-shelter/micro-shelter-014.png",
      "public/portfolio/full/micro-shelter/micro-shelter-015.jpg",
      "public/portfolio/full/micro-shelter/micro-shelter-016.png",
      "public/portfolio/full/micro-shelter/micro-shelter-017.png",
      "public/portfolio/full/micro-shelter/micro-shelter-018.jpg"
    ],
    "summary": "A compact housing study exploring privacy, density, and livable space in a small urban footprint.",
    "notes": [
      "Studied Hong Kong micro-living conditions and spatial constraints.",
      "Tested how furniture, circulation, and daylight can make a small room feel usable.",
      "Developed the project through reference images, model views, and final presentation studies."
    ]
  },
  {
    "id": "river-house",
    "title": "River House",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/river-house/river-house-001.jpg",
    "images": [
      "public/portfolio/full/river-house/river-house-001.jpg",
      "public/portfolio/full/river-house/river-house-002.jpg",
      "public/portfolio/full/river-house/river-house-003.jpg",
      "public/portfolio/full/river-house/river-house-004.jpg",
      "public/portfolio/full/river-house/river-house-005.jpg",
      "public/portfolio/full/river-house/river-house-006.jpg",
      "public/portfolio/full/river-house/river-house-007.jpg",
      "public/portfolio/full/river-house/river-house-008.jpg",
      "public/portfolio/full/river-house/river-house-009.jpg",
      "public/portfolio/full/river-house/river-house-010.jpg",
      "public/portfolio/full/river-house/river-house-011.jpg",
      "public/portfolio/full/river-house/river-house-012.jpg",
      "public/portfolio/full/river-house/river-house-013.png",
      "public/portfolio/full/river-house/river-house-014.png",
      "public/portfolio/full/river-house/river-house-015.png"
    ],
    "summary": "A residential design that studies how a building can sit near water while keeping a calm connection to landscape.",
    "notes": [
      "Explored massing, views, and the relationship between structure and terrain.",
      "Used multiple views to test how the house meets the river edge.",
      "Focused on balance between shelter, openness, and site movement."
    ]
  },
  {
    "id": "villa-savoye",
    "title": "Villa Savoye Plastic Set",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2023",
    "cover": "public/portfolio/full/villa-savoye/villa-savoye-001.jpg",
    "images": [
      "public/portfolio/full/villa-savoye/villa-savoye-001.jpg",
      "public/portfolio/full/villa-savoye/villa-savoye-002.jpg",
      "public/portfolio/full/villa-savoye/villa-savoye-003.jpg",
      "public/portfolio/full/villa-savoye/villa-savoye-004.jpg",
      "public/portfolio/full/villa-savoye/villa-savoye-005.jpg"
    ],
    "summary": "A physical architecture study using plastic components to understand proportion, elevation, and modernist form.",
    "notes": [
      "Built from modular pieces to study planes, columns, and clean architectural geometry.",
      "Observed how simple forms can create strong spatial rhythm.",
      "Used the model as a way to learn from an important architectural precedent."
    ]
  },
  {
    "id": "fallingwater",
    "title": "Fallingwater Wood Set",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2025",
    "cover": "public/portfolio/full/fallingwater/fallingwater-001.jpg",
    "images": [
      "public/portfolio/full/fallingwater/fallingwater-001.jpg",
      "public/portfolio/full/fallingwater/fallingwater-002.jpg",
      "public/portfolio/full/fallingwater/fallingwater-003.jpg",
      "public/portfolio/full/fallingwater/fallingwater-004.jpg",
      "public/portfolio/full/fallingwater/fallingwater-005.jpg",
      "public/portfolio/full/fallingwater/fallingwater-006.jpg",
      "public/portfolio/full/fallingwater/fallingwater-007.jpg"
    ],
    "summary": "A wood model study focused on layered horizontal forms, cantilevers, and the dialogue between building and nature.",
    "notes": [
      "Explored material warmth and structural layering through model construction.",
      "Compared overlapping planes and supports to understand balance.",
      "Practiced precision, patience, and assembly through a physical build."
    ]
  },
  {
    "id": "forgotten-peak",
    "title": "Forgotten Peak Middle-High School",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/forgotten-peak/forgotten-peak-001.jpg",
    "images": [
      "public/portfolio/full/forgotten-peak/forgotten-peak-001.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-002.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-003.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-004.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-005.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-006.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-007.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-008.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-009.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-010.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-011.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-012.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-013.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-014.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-015.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-016.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-017.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-018.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-019.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-020.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-021.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-022.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-023.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-024.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-025.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-026.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-027.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-028.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-029.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-030.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-031.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-032.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-033.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-034.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-035.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-036.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-037.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-038.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-039.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-040.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-041.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-042.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-043.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-044.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-045.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-046.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-047.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-048.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-049.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-050.jpg",
      "public/portfolio/full/forgotten-peak/forgotten-peak-051.png"
    ],
    "summary": "A school design concept considering learning spaces, circulation, and a memorable campus identity.",
    "notes": [
      "Designed around how students move between public, shared, and quieter areas.",
      "Explored how a school can feel both structured and welcoming.",
      "Used the project to connect architecture with daily student experience."
    ]
  },
  {
    "id": "contemporary-museum",
    "title": "Contemporary Museum",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/contemporary-museum/contemporary-museum-001.jpg",
    "images": [
      "public/portfolio/full/contemporary-museum/contemporary-museum-001.jpg",
      "public/portfolio/full/contemporary-museum/contemporary-museum-002.jpg",
      "public/portfolio/full/contemporary-museum/contemporary-museum-003.jpg",
      "public/portfolio/full/contemporary-museum/contemporary-museum-004.jpg",
      "public/portfolio/full/contemporary-museum/contemporary-museum-005.jpg"
    ],
    "summary": "A museum concept studying public space, exhibition flow, and the way visitors encounter art and architecture.",
    "notes": [
      "Organized galleries and open areas around the visitor journey.",
      "Considered how scale and light can make a museum feel calm but active.",
      "Developed the project as both an architecture and art-viewing experience."
    ]
  },
  {
    "id": "highrise-building",
    "title": "Highrise Building",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/highrise-building/highrise-building-001.jpg",
    "images": [
      "public/portfolio/full/highrise-building/highrise-building-001.jpg",
      "public/portfolio/full/highrise-building/highrise-building-002.jpg",
      "public/portfolio/full/highrise-building/highrise-building-003.jpg",
      "public/portfolio/full/highrise-building/highrise-building-004.jpg",
      "public/portfolio/full/highrise-building/highrise-building-005.jpg",
      "public/portfolio/full/highrise-building/highrise-building-006.jpg",
      "public/portfolio/full/highrise-building/highrise-building-007.jpg",
      "public/portfolio/full/highrise-building/highrise-building-008.jpg",
      "public/portfolio/full/highrise-building/highrise-building-009.jpg",
      "public/portfolio/full/highrise-building/highrise-building-010.jpg",
      "public/portfolio/full/highrise-building/highrise-building-011.jpg",
      "public/portfolio/full/highrise-building/highrise-building-012.jpg",
      "public/portfolio/full/highrise-building/highrise-building-013.jpg",
      "public/portfolio/full/highrise-building/highrise-building-014.jpg",
      "public/portfolio/full/highrise-building/highrise-building-015.jpg",
      "public/portfolio/full/highrise-building/highrise-building-016.jpg",
      "public/portfolio/full/highrise-building/highrise-building-017.jpg",
      "public/portfolio/full/highrise-building/highrise-building-018.jpg",
      "public/portfolio/full/highrise-building/highrise-building-019.jpg",
      "public/portfolio/full/highrise-building/highrise-building-020.jpg",
      "public/portfolio/full/highrise-building/highrise-building-021.jpg",
      "public/portfolio/full/highrise-building/highrise-building-022.jpg",
      "public/portfolio/full/highrise-building/highrise-building-023.jpg",
      "public/portfolio/full/highrise-building/highrise-building-024.jpg",
      "public/portfolio/full/highrise-building/highrise-building-025.jpg"
    ],
    "summary": "A vertical architecture study exploring height, structure, and repeated spatial systems.",
    "notes": [
      "Studied how a tall building can organize repeated floors while still feeling designed.",
      "Explored proportion, facade rhythm, and the relationship between base and tower.",
      "Used multiple views to compare the overall massing with smaller details."
    ]
  },
  {
    "id": "motel-hotel",
    "title": "Motel / Hotel",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/motel-hotel/motel-hotel-001.jpg",
    "images": [
      "public/portfolio/full/motel-hotel/motel-hotel-001.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-002.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-003.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-004.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-005.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-006.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-007.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-008.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-009.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-010.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-011.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-012.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-013.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-014.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-015.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-016.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-017.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-018.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-019.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-020.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-021.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-022.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-023.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-024.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-025.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-026.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-027.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-028.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-029.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-030.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-031.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-032.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-033.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-034.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-035.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-036.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-037.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-038.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-039.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-040.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-041.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-042.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-043.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-044.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-045.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-046.jpg",
      "public/portfolio/full/motel-hotel/motel-hotel-047.jpg"
    ],
    "summary": "A hospitality design study about rooms, circulation, privacy, and the feeling of arrival.",
    "notes": [
      "Considered how guests move from public entry spaces into more private rooms.",
      "Tested repeated room modules and how they combine into a larger building.",
      "Focused on making the project readable as both a plan and an experience."
    ]
  },
  {
    "id": "cradle-cafe",
    "title": "Cradle-Cafe",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/cradle-cafe/cradle-cafe-001.jpg",
    "images": [
      "public/portfolio/full/cradle-cafe/cradle-cafe-001.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-002.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-003.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-004.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-005.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-006.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-007.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-008.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-009.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-010.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-011.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-012.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-013.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-014.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-015.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-016.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-017.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-018.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-019.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-020.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-021.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-022.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-023.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-024.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-025.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-026.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-027.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-028.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-029.jpg",
      "public/portfolio/full/cradle-cafe/cradle-cafe-030.jpg"
    ],
    "summary": "A small public-space concept combining cafe atmosphere with a soft, welcoming architectural form.",
    "notes": [
      "Explored how a cafe can feel protected, warm, and open at the same time.",
      "Used form and enclosure to suggest a calm place for gathering.",
      "Balanced expressive shape with practical circulation and seating space."
    ]
  },
  {
    "id": "church",
    "title": "Church",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/church/church-001.jpg",
    "images": [
      "public/portfolio/full/church/church-001.jpg",
      "public/portfolio/full/church/church-002.jpg",
      "public/portfolio/full/church/church-003.jpg",
      "public/portfolio/full/church/church-004.jpg",
      "public/portfolio/full/church/church-005.jpg",
      "public/portfolio/full/church/church-006.jpg",
      "public/portfolio/full/church/church-007.jpg",
      "public/portfolio/full/church/church-008.jpg",
      "public/portfolio/full/church/church-009.jpg",
      "public/portfolio/full/church/church-010.jpg",
      "public/portfolio/full/church/church-011.jpg",
      "public/portfolio/full/church/church-012.jpg",
      "public/portfolio/full/church/church-013.jpg",
      "public/portfolio/full/church/church-014.jpg",
      "public/portfolio/full/church/church-015.jpg",
      "public/portfolio/full/church/church-016.jpg",
      "public/portfolio/full/church/church-017.jpg",
      "public/portfolio/full/church/church-018.jpg",
      "public/portfolio/full/church/church-019.jpg",
      "public/portfolio/full/church/church-020.jpg",
      "public/portfolio/full/church/church-021.jpg",
      "public/portfolio/full/church/church-022.jpg",
      "public/portfolio/full/church/church-023.jpg",
      "public/portfolio/full/church/church-024.jpg",
      "public/portfolio/full/church/church-025.jpg",
      "public/portfolio/full/church/church-026.jpg",
      "public/portfolio/full/church/church-027.jpg",
      "public/portfolio/full/church/church-028.png",
      "public/portfolio/full/church/church-029.png"
    ],
    "summary": "A sacred-space study focused on light, quietness, gathering, and architectural atmosphere.",
    "notes": [
      "Studied how height, openings, and simple forms can create a contemplative mood.",
      "Explored procession and the relationship between entrance, seating, and focal space.",
      "Used the project to practice designing emotional experience through architecture."
    ]
  },
  {
    "id": "dorm",
    "title": "Something Like a Dorm",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/dorm/dorm-001.jpg",
    "images": [
      "public/portfolio/full/dorm/dorm-001.jpg",
      "public/portfolio/full/dorm/dorm-002.jpg",
      "public/portfolio/full/dorm/dorm-003.jpg",
      "public/portfolio/full/dorm/dorm-004.jpg",
      "public/portfolio/full/dorm/dorm-005.jpg",
      "public/portfolio/full/dorm/dorm-006.jpg",
      "public/portfolio/full/dorm/dorm-007.jpg",
      "public/portfolio/full/dorm/dorm-008.jpg",
      "public/portfolio/full/dorm/dorm-009.jpg",
      "public/portfolio/full/dorm/dorm-010.jpg",
      "public/portfolio/full/dorm/dorm-011.jpg",
      "public/portfolio/full/dorm/dorm-012.jpg",
      "public/portfolio/full/dorm/dorm-013.jpg",
      "public/portfolio/full/dorm/dorm-014.jpg",
      "public/portfolio/full/dorm/dorm-015.jpg",
      "public/portfolio/full/dorm/dorm-016.jpg",
      "public/portfolio/full/dorm/dorm-017.jpg",
      "public/portfolio/full/dorm/dorm-018.jpg",
      "public/portfolio/full/dorm/dorm-019.jpg",
      "public/portfolio/full/dorm/dorm-020.jpg",
      "public/portfolio/full/dorm/dorm-021.jpg",
      "public/portfolio/full/dorm/dorm-022.jpg",
      "public/portfolio/full/dorm/dorm-023.jpg",
      "public/portfolio/full/dorm/dorm-024.jpg",
      "public/portfolio/full/dorm/dorm-025.jpg",
      "public/portfolio/full/dorm/dorm-026.png",
      "public/portfolio/full/dorm/dorm-027.png"
    ],
    "summary": "A student-housing concept exploring shared living, privacy, and daily routines.",
    "notes": [
      "Organized spaces around the balance between individual rooms and common areas.",
      "Considered how circulation can make a dorm feel social but not crowded.",
      "Connected the project to boarding-school life and how students use space every day."
    ]
  },
  {
    "id": "bloom-nest",
    "title": "Bloom Nest",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/bloom-nest/bloom-nest-001.jpg",
    "images": [
      "public/portfolio/full/bloom-nest/bloom-nest-001.jpg",
      "public/portfolio/full/bloom-nest/bloom-nest-002.jpg",
      "public/portfolio/full/bloom-nest/bloom-nest-003.png",
      "public/portfolio/full/bloom-nest/bloom-nest-004.png",
      "public/portfolio/full/bloom-nest/bloom-nest-005.png",
      "public/portfolio/full/bloom-nest/bloom-nest-006.png"
    ],
    "summary": "A nature-inspired building concept exploring curved enclosure, gathering, and a soft structural identity.",
    "notes": [
      "Used organic form language to study how a building can feel protective and open.",
      "Compared exterior views and presentation images to refine the overall identity.",
      "Temporary caption: add exact materials, site idea, and design challenge when ready."
    ]
  },
  {
    "id": "bridge",
    "title": "Bridge",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/bridge/bridge-001.jpg",
    "images": [
      "public/portfolio/full/bridge/bridge-001.jpg",
      "public/portfolio/full/bridge/bridge-002.jpg",
      "public/portfolio/full/bridge/bridge-003.jpg",
      "public/portfolio/full/bridge/bridge-004.jpg",
      "public/portfolio/full/bridge/bridge-005.jpg",
      "public/portfolio/full/bridge/bridge-006.jpg"
    ],
    "summary": "A structural study focused on spanning, support, and the visual rhythm of a crossing.",
    "notes": [
      "Explored how repeated structural parts can create both strength and pattern.",
      "Used multiple angles to show the bridge as an object and as a system.",
      "Temporary caption: add span, materials, and construction process notes."
    ]
  },
  {
    "id": "chinese-joint",
    "title": "Chinese Joint",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/chinese-joint/chinese-joint-001.jpg",
    "images": [
      "public/portfolio/full/chinese-joint/chinese-joint-001.jpg",
      "public/portfolio/full/chinese-joint/chinese-joint-002.jpg",
      "public/portfolio/full/chinese-joint/chinese-joint-003.jpg"
    ],
    "summary": "A joinery-focused architectural detail study inspired by traditional construction connections.",
    "notes": [
      "Studied how small connection details can shape a larger structural language.",
      "Focused on craft, fit, and the relationship between parts.",
      "Temporary caption: add the specific joint type and what you learned from building it."
    ]
  },
  {
    "id": "museum-study",
    "title": "Something Like a Museum",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/museum-study/museum-study-001.jpg",
    "images": [
      "public/portfolio/full/museum-study/museum-study-001.jpg",
      "public/portfolio/full/museum-study/museum-study-002.jpg",
      "public/portfolio/full/museum-study/museum-study-003.jpg",
      "public/portfolio/full/museum-study/museum-study-004.jpg"
    ],
    "summary": "A museum-like spatial study exploring public entry, form, and the movement of visitors through a cultural building.",
    "notes": [
      "Compared views to understand how the massing reads from different approaches.",
      "Thought about how a public building can guide people without feeling rigid.",
      "Temporary caption: add the exhibition idea and any plan or circulation notes."
    ]
  },
  {
    "id": "golden-chinese-temple",
    "title": "Golden Chinese Temple",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-001.jpg",
    "images": [
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-001.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-002.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-003.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-004.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-005.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-006.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-007.jpg",
      "public/portfolio/full/golden-chinese-temple/golden-chinese-temple-008.jpg"
    ],
    "summary": "A temple model study examining ornament, symmetry, roof form, and cultural architectural references.",
    "notes": [
      "Observed how rooflines, color, and detail create a recognizable sacred building.",
      "Practiced translating architectural reference into a physical model.",
      "Temporary caption: add materials and what architectural details mattered most."
    ]
  },
  {
    "id": "popsicle-sticks",
    "title": "Popsicle Sticks",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/popsicle-sticks/popsicle-sticks-001.jpg",
    "images": [
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-001.jpg",
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-002.jpg",
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-003.jpg",
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-004.jpg",
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-005.jpg",
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-006.jpg",
      "public/portfolio/full/popsicle-sticks/popsicle-sticks-007.jpg"
    ],
    "summary": "A material construction exercise using repeated wood sticks to test structure, pattern, and assembly.",
    "notes": [
      "Used a simple material to explore rhythm, support, and craft.",
      "Worked through the physical limits of repeated modules and glue-up construction.",
      "Temporary caption: add the design goal, dimensions, and any mistakes you solved."
    ]
  },
  {
    "id": "moveable-lego",
    "title": "Small Move-Able Lego Projects",
    "category": "electronic-engineering",
    "categoryLabel": "Electronic Engineering",
    "year": "2026",
    "cover": "public/portfolio/full/moveable-lego/moveable-lego-001.jpg",
    "images": [
      "public/portfolio/full/moveable-lego/moveable-lego-001.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-002.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-003.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-004.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-005.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-006.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-007.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-008.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-009.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-010.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-011.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-012.jpg",
      "public/portfolio/full/moveable-lego/moveable-lego-013.jpg"
    ],
    "summary": "Small modular builds exploring movement, transformable parts, and quick physical prototyping.",
    "notes": [
      "Used Lego as a fast way to test structure and moving relationships.",
      "Focused on iteration, adjustability, and how parts connect.",
      "Temporary caption: add what moves, what problem it solves, and the best iteration."
    ]
  },
  {
    "id": "hide-away-cabin",
    "title": "Hide-Away Cabin",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/hide-away-cabin/hide-away-cabin-001.jpg",
    "images": [
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-001.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-002.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-003.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-004.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-005.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-006.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-007.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-008.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-009.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-010.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-011.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-012.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-013.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-014.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-015.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-016.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-017.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-018.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-019.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-020.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-021.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-022.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-023.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-024.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-025.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-026.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-027.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-028.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-029.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-030.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-031.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-032.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-033.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-034.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-035.jpg",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-036.png",
      "public/portfolio/full/hide-away-cabin/hide-away-cabin-037.png"
    ],
    "summary": "A compact retreat concept studying privacy, shelter, and a quiet relationship to its surroundings.",
    "notes": [
      "Explored how a small building can feel secluded but still carefully composed.",
      "Used model images to test form, openings, and the sense of enclosure.",
      "Temporary caption: add the site story and material choices when ready."
    ]
  },
  {
    "id": "freehand-sketch",
    "title": "Freehand Sketches",
    "category": "architecture",
    "categoryLabel": "Architecture",
    "year": "2026",
    "cover": "public/portfolio/full/freehand-sketch/freehand-sketch-001.jpg",
    "images": [
      "public/portfolio/full/freehand-sketch/freehand-sketch-001.jpg",
      "public/portfolio/full/freehand-sketch/freehand-sketch-002.jpg",
      "public/portfolio/full/freehand-sketch/freehand-sketch-003.jpg",
      "public/portfolio/full/freehand-sketch/freehand-sketch-004.jpg"
    ],
    "summary": "A chronological sketching study showing observation, line confidence, and form exploration.",
    "notes": [
      "Practiced drawing by hand to improve proportion and visual memory.",
      "Used quick linework to capture structure before adding detail.",
      "Kept the work loose enough to show process and decision-making."
    ]
  },
  {
    "id": "circuits",
    "title": "Circuit Studies",
    "category": "electronic-engineering",
    "categoryLabel": "Electronic Engineering",
    "year": "2022",
    "cover": "public/portfolio/full/circuits/circuits-001.jpg",
    "images": [
      "public/portfolio/full/circuits/circuits-001.jpg",
      "public/portfolio/full/circuits/circuits-002.jpg",
      "public/portfolio/full/circuits/circuits-003.jpg",
      "public/portfolio/full/circuits/circuits-004.jpg",
      "public/portfolio/full/circuits/circuits-005.jpg",
      "public/portfolio/full/circuits/circuits-006.jpg",
      "public/portfolio/full/circuits/circuits-007.jpg",
      "public/portfolio/full/circuits/circuits-008.jpg",
      "public/portfolio/full/circuits/circuits-009.jpg",
      "public/portfolio/full/circuits/circuits-010.jpg",
      "public/portfolio/full/circuits/circuits-011.jpg",
      "public/portfolio/full/circuits/circuits-012.jpg",
      "public/portfolio/full/circuits/circuits-013.jpg",
      "public/portfolio/full/circuits/circuits-014.jpg",
      "public/portfolio/full/circuits/circuits-015.jpg",
      "public/portfolio/full/circuits/circuits-016.jpg",
      "public/portfolio/full/circuits/circuits-017.jpg",
      "public/portfolio/full/circuits/circuits-018.jpg",
      "public/portfolio/full/circuits/circuits-019.jpg"
    ],
    "summary": "Electronic Engineering experiments with circuits, components, testing, and hands-on prototyping.",
    "notes": [
      "Built and tested circuit arrangements with physical components.",
      "Used wiring and boards to understand how systems connect and respond.",
      "Shows curiosity across making, engineering, and visual design."
    ]
  }
];
